{
 "title": "Node Drilldown",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "proxy_type", "query": { "query": "label_values(type)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values({type=\"$proxy_type\"},node)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_node_health{type=\"$proxy_type\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_request_status_count{type=\"$proxy_type\", node=\"$node\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total Requests Handled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_request_count{type=\"$proxy_type\", node=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(proxy_request_status_count{type=\"$proxy_type\", node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Status Code Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_request_status_count{type=\"$proxy_type\", node=\"$node\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}