{
 "title": "Proxy Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "proxy_type",
    "label": "Proxy Type",
    "query": {
     "query": "label_values(proxy_node_count,type)"
    }
   },
   { "name": "datasource", "label": "Datasources", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Healthy Nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "proxy_node_count", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Total RPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(proxy_request_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(proxy_request_count[1m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total Served Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(proxy_request_count)", "legendFormat": "__auto" }
   ]
  },
  { "title": "$proxy_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "proxy_type" },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(proxy_request_count{type=\"$proxy_type\"}[1m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(proxy_request_status_count{type=\"$proxy_type\"}[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "proxy_node_health{type=\"$proxy_type\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}