server:
  listen: ":8080"
  listen_grpc: ":9091"
  timeouts:
    read: "10s"
    write: "10s"
    idle: "10s"

tls:
  autocert:
    email: ""
    hosts: []
  cert: "./localhost.pem"
  key: "./localhost-key.pem"

seed:
  url: "https://raw.githubusercontent.com/cosmos/chain-registry/master/akash/chain.json"
  refresh_interval: "5m"
  chain_id: "akashnet-2"

health:
  healthy_threshold: "10s"
  proxy_request_timeout: "15s"

cors:
  allow_origin: "*"
  allow_methods: "GET, POST, PUT, DELETE, OPTIONS"
  allow_headers: "Content-Type, Authorization"