name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
      - uses: actions/checkout@v4
      - run: go mod download
      - run: go build -v ./...
      - run: go test -v -cover -timeout=30s ./...
